version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "12001:12001"
    volumes:
      - ./uploads:/app/uploads
      - ./database:/app/database
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///database/wedding_photos.db
      - UPLOAD_FOLDER=/app/uploads
    depends_on:
      - db
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "12000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:12001/api
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=wedding_photos
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data: